onboarding = false

[theme]
name = "terminal"
auto_switch = false

[ui.sound]
enabled = false

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_sort = "spaces"
pane_gaps = false

[keys]
prefix = 'ctrl+a'
